
unless Vagrant.has_plugin?("vagrant-vbguest")
  system('vagrant plugin install vagrant-vbguest')
end

unless Vagrant.has_plugin?("vagrant-reload")
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure("2") do |config|
  config.vm.define "iotBox" do |iotBox|
    iotBox.vm.box = "ubuntu/bionic64"
    iotBox.vm.provider "virtualbox" do |v|
      v.name = "iotBox"
    end
    iotBox.vm.provision :shell, path: "setup.sh"
    iotBox.vm.provision :reload
  end
end
